import { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import React, { ReactNode } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "mentorship",
  description: "Generated by create next app",
};
const date = new Date();
const year = date.getFullYear();
export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  container mx-auto max-w-[1336px] relative`}
      >
        <header className="py-2">
          <Link href="/" className="font-pacifico">
            <h1 className="lg:text-2xl text-xl  text-[#14A800]">Mentorship</h1>
          </Link>
        </header>
        <main>{children}</main>
        <div className="container my-3 mx-auto max-w-[1336px] bg-gray-900  text-center text-white bottom-0 py-16">
          &copy; {year} Mentorship &reg; plc. all right are reserved.
        </div>
      </body>
    </html>
  );
}
