import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Footer from "@/components/homePage/Footer";
import Redux_Provider from "../Redux_Provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import MentorNavBar from "@/components/MentorDashbord/MentorNavBar";
import MenteeNavBar from "@/components/menteeDashboard/MenteeNavNBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "mentorship",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} container mx-auto max-w-[1336px] relative`}
      >
        <Redux_Provider>
          <MentorNavBar />
          <main>{children}</main>
          <MenteeNavBar />
          <main className="mt-20">{children}</main>
          <ToastContainer />
          <Footer />
        </Redux_Provider>
      </body>
    </html>
  );
}
