import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Footer from "@/components/homePage/Footer";
import Redux_Provider from "../Redux_Provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import MenteeNavBar from "@/components/menteeDashboard/MenteeNavNBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "mentorship",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full flex flex-col relative`}>
        <Redux_Provider>
          <MenteeNavBar />
          <main className="mt-20 flex-grow container mx-auto max-w-screen-2xl ">
            {children}
          </main>
          <ToastContainer />
          <Footer />
        </Redux_Provider>
      </body>
    </html>
  );
}
