import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavgationBar } from "@/app/route";
import { Footers } from "./route/Footers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} container mx-auto max-w-[1336px] relative`}
      >
        <NavgationBar />
        {children}
      </body>
      <Footers />
    </html>
  );
}
