import AdminSideBar from "@/components/admin/AdminSideBar";
import "../globals.css";
import MainPart from "@/components/admin/MainPart";
import Redux_Provider from "../Redux_Provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex text-gray-800 font-inter relative ">
        <Redux_Provider>
          <AdminSideBar />
          <MainPart>{children}</MainPart>
          <ToastContainer />
        </Redux_Provider>
      </body>
    </html>
  );
}
